# Generated by Django 5.1.15 on 2026-05-15 10:03

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('billing', '0001_initial'),
        ('classes', '0001_initial'),
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earning_source', models.CharField(choices=[('student_payment', 'Student Payment'), ('manual_adjustment', 'Manual Adjustment'), ('fixed_salary', 'Fixed Salary'), ('package_course', 'Package Course'), ('other', 'Other')], db_index=True, default='other', max_length=30)),
                ('earning_date_ad', models.DateField(db_index=True)),
                ('earning_date_bs', models.CharField(blank=True, max_length=10)),
                ('period_label', models.CharField(blank=True, max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('partial', 'Partial'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_earnings', to='academic.academicperiod')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_earnings', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_earnings', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_earnings', to='organizations.branch')),
                ('class_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_earnings', to='classes.classenrollment')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_earnings', to='classes.classroom')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_earnings', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_earnings', to='organizations.organization')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_earnings', to='students.student')),
                ('student_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_earnings', to='billing.studentpayment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='teachers.teacher')),
            ],
            options={
                'ordering': ['teacher', '-earning_date_ad', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('draft_voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date_ad', models.DateField(db_index=True)),
                ('payment_date_bs', models.CharField(blank=True, max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('online', 'Online'), ('cheque', 'Cheque'), ('wallet', 'Wallet'), ('other', 'Other')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('acknowledgement_file_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('voided', 'Voided')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payments', to='academic.academicperiod')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payments', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_payments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payments', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_payments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payments', to='organizations.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='teachers.teacher')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_teacher_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date_ad', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deduction_type', models.CharField(choices=[('advance_recovery', 'Advance Recovery'), ('tax', 'Tax'), ('absence', 'Absence'), ('adjustment', 'Adjustment'), ('other', 'Other')], default='other', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_deductions', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_deductions', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_deductions', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_deductions', to='organizations.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='teachers.teacher')),
                ('teacher_earning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='payroll.teacherearning')),
                ('teacher_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deductions', to='payroll.teacherpayment')),
            ],
            options={
                'ordering': ['teacher', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('teacher_earning', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='payroll.teacherearning')),
                ('teacher_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payroll.teacherpayment')),
            ],
            options={
                'ordering': ['teacher_payment', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPaymentBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('batch_date_ad', models.DateField(db_index=True)),
                ('batch_date_bs', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payment_batches', to='academic.academicperiod')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payment_batches', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teacher_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payment_batches', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_payment_batches', to='organizations.organization')),
            ],
            options={
                'ordering': ['-batch_date_ad', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='teacherpayment',
            name='payment_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payroll.teacherpaymentbatch'),
        ),
        migrations.AddIndex(
            model_name='teacherearning',
            index=models.Index(fields=['organization', 'status'], name='payroll_tea_organiz_83f812_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherearning',
            index=models.Index(fields=['branch', 'status'], name='payroll_tea_branch__6fc5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherearning',
            index=models.Index(fields=['academic_year', 'status'], name='payroll_tea_academi_7582ae_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherearning',
            index=models.Index(fields=['teacher', 'status'], name='payroll_tea_teacher_4b47d0_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherearning',
            index=models.Index(fields=['earning_source', 'status'], name='payroll_tea_earning_c6e861_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherearning',
            index=models.Index(fields=['earning_date_ad'], name='payroll_tea_earning_5ef896_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherearning',
            constraint=models.CheckConstraint(condition=models.Q(('gross_amount__gte', 0)), name='teacher_earning_gross_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='teacherearning',
            constraint=models.CheckConstraint(condition=models.Q(('deduction_amount__gte', 0)), name='teacher_earning_deduction_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='teacherearning',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='teacher_earning_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='teacherearning',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='teacher_earning_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='teacherearning',
            constraint=models.CheckConstraint(condition=models.Q(('balance_amount__gte', 0)), name='teacher_earning_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='teacherdeduction',
            index=models.Index(fields=['organization', 'status'], name='payroll_tea_organiz_7e10cf_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherdeduction',
            index=models.Index(fields=['branch', 'status'], name='payroll_tea_branch__0ecc83_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherdeduction',
            index=models.Index(fields=['academic_year', 'status'], name='payroll_tea_academi_d78d55_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherdeduction',
            index=models.Index(fields=['teacher', 'status'], name='payroll_tea_teacher_82c253_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherdeduction',
            index=models.Index(fields=['deduction_type', 'status'], name='payroll_tea_deducti_db42a9_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherdeduction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='teacher_deduction_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentallocation',
            index=models.Index(fields=['teacher_payment'], name='payroll_tea_teacher_9601d9_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentallocation',
            index=models.Index(fields=['teacher_earning'], name='payroll_tea_teacher_541145_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_allocated__gt', 0)), name='teacher_payment_allocation_positive'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentbatch',
            index=models.Index(fields=['organization', 'status'], name='payroll_tea_organiz_19a27b_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentbatch',
            index=models.Index(fields=['branch', 'status'], name='payroll_tea_branch__e127c3_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentbatch',
            index=models.Index(fields=['academic_year', 'status'], name='payroll_tea_academi_a90c00_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentbatch',
            index=models.Index(fields=['batch_number'], name='payroll_tea_batch_n_075e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpaymentbatch',
            index=models.Index(fields=['batch_date_ad'], name='payroll_tea_batch_d_cbfe0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherpaymentbatch',
            constraint=models.UniqueConstraint(fields=('organization', 'batch_number'), name='unique_teacher_batch_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='teacherpaymentbatch',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='teacher_batch_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='teacherpayment',
            index=models.Index(fields=['organization', 'status'], name='payroll_tea_organiz_c22511_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpayment',
            index=models.Index(fields=['branch', 'status'], name='payroll_tea_branch__799024_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpayment',
            index=models.Index(fields=['academic_year', 'status'], name='payroll_tea_academi_0aed0a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpayment',
            index=models.Index(fields=['teacher', 'status'], name='payroll_tea_teacher_52fc5c_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpayment',
            index=models.Index(fields=['payment_method', 'status'], name='payroll_tea_payment_429dea_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpayment',
            index=models.Index(fields=['voucher_number'], name='payroll_tea_voucher_3e9868_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpayment',
            index=models.Index(fields=['draft_voucher_number'], name='payroll_tea_draft_v_a9420d_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherpayment',
            index=models.Index(fields=['payment_date_ad'], name='payroll_tea_payment_7c0486_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('voucher_number__isnull', False)), fields=('organization', 'voucher_number'), name='unique_teacher_voucher_number_per_org_when_set'),
        ),
        migrations.AddConstraint(
            model_name='teacherpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('draft_voucher_number__isnull', False)), fields=('organization', 'draft_voucher_number'), name='unique_teacher_draft_voucher_number_per_org_when_set'),
        ),
        migrations.AddConstraint(
            model_name='teacherpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='teacher_payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='teacherpayment',
            constraint=models.CheckConstraint(condition=models.Q(('deduction_amount__gte', 0)), name='teacher_payment_deduction_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='teacherpayment',
            constraint=models.CheckConstraint(condition=models.Q(('net_paid_amount__gte', 0)), name='teacher_payment_net_non_negative'),
        ),
    ]
