# Generated by Django 5.1.15 on 2026-05-15 05:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family_code', models.CharField(max_length=50)),
                ('primary_contact_name', models.CharField(max_length=255)),
                ('primary_contact_number', models.CharField(db_index=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='families', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='organizations.organization')),
            ],
            options={
                'ordering': ['family_code'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('local_guardian', 'Local Guardian'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=30)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('alternate_phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guardians', to='organizations.branch')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardians', to='guardians.family')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='organizations.organization')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('local_guardian', 'Local Guardian'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=30)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_receive_notifications', models.BooleanField(default=True)),
                ('can_make_payments', models.BooleanField(default=True)),
                ('can_request_refunds', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='guardians.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='students.student')),
            ],
            options={
                'ordering': ['student', '-is_primary', 'guardian__full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['organization', 'is_active'], name='guardians_f_organiz_6b17f2_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['branch', 'is_active'], name='guardians_f_branch__57d9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['family_code'], name='guardians_f_family__dad84b_idx'),
        ),
        migrations.AddConstraint(
            model_name='family',
            constraint=models.UniqueConstraint(fields=('organization', 'family_code'), name='unique_family_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['organization', 'is_active'], name='guardians_g_organiz_916c11_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['branch', 'is_active'], name='guardians_g_branch__73e840_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['phone'], name='guardians_g_phone_b2648e_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['full_name'], name='guardians_g_full_na_a25eb1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentguardian',
            index=models.Index(fields=['student', 'is_primary'], name='guardians_s_student_d1380f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentguardian',
            index=models.Index(fields=['guardian'], name='guardians_s_guardia_98a9e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentguardian',
            constraint=models.UniqueConstraint(fields=('student', 'guardian'), name='unique_student_guardian_link'),
        ),
    ]
