# Generated by Django 5.1.15 on 2026-05-15 05:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('post', 'Post'), ('reverse', 'Reverse'), ('void', 'Void'), ('approve', 'Approve'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('system', 'System')], db_index=True, max_length=50)),
                ('module', models.CharField(choices=[('accounts', 'Accounts'), ('organizations', 'Organizations'), ('academic', 'Academic'), ('accounting', 'Accounting'), ('billing', 'Billing'), ('payroll', 'Payroll'), ('students', 'Students'), ('teachers', 'Teachers'), ('classes', 'Classes'), ('system', 'System')], db_index=True, max_length=50)),
                ('object_type', models.CharField(db_index=True, max_length=150)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('before_data', models.JSONField(blank=True, null=True)),
                ('after_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.branch')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'module', 'action'], name='common_audi_organiz_cc76fc_idx'), models.Index(fields=['branch', 'module', 'action'], name='common_audi_branch__b55405_idx'), models.Index(fields=['user', 'created_at'], name='common_audi_user_id_8b57b8_idx'), models.Index(fields=['object_type', 'object_id'], name='common_audi_object__a9d982_idx')],
            },
        ),
    ]
