# Generated by Django 5.1.15 on 2026-05-15 05:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20)),
                ('date_of_birth_ad', models.DateField(blank=True, null=True)),
                ('date_of_birth_bs', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('permanent_address', models.TextField()),
                ('temporary_address', models.TextField(blank=True)),
                ('school_college_name', models.CharField(blank=True, max_length=255)),
                ('current_grade_class', models.CharField(blank=True, max_length=100)),
                ('photo_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('inquiry', 'Inquiry'), ('pending', 'Pending'), ('active', 'Active'), ('on_break', 'On Break'), ('left', 'Left'), ('graduated', 'Graduated'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admission_date_ad', models.DateField(blank=True, null=True)),
                ('admission_date_bs', models.CharField(blank=True, max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_students', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organizations.organization')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=255)),
                ('board_university', models.CharField(blank=True, max_length=255)),
                ('level_grade', models.CharField(max_length=100)),
                ('result_type', models.CharField(max_length=100)),
                ('gpa_percentage_grade', models.CharField(blank=True, max_length=100)),
                ('passed_year_bs', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passed_year_ad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
            ],
            options={
                'ordering': ['student', '-passed_year_ad', '-passed_year_bs'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('photo', 'Photo'), ('birth_certificate', 'Birth Certificate'), ('marksheet', 'Marksheet'), ('citizenship', 'Citizenship'), ('transfer_certificate', 'Transfer Certificate'), ('other', 'Other')], max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_documents', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_documents', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_student_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student', 'document_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_full_name', models.CharField(max_length=255)),
                ('guardian_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interested_class_subject', models.CharField(blank=True, max_length=255)),
                ('inquiry_source', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('appointment_scheduled', 'Appointment Scheduled'), ('converted', 'Converted'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_inquiries', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_inquiries', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_inquiries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_inquiries', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('behavior', 'Behavior'), ('health', 'Health'), ('finance', 'Finance'), ('other', 'Other')], db_index=True, default='general', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('attachment_path', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_notes', to='students.student')),
            ],
            options={
                'ordering': ['student', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_college_name', models.CharField(max_length=255)),
                ('level_class_attended', models.CharField(max_length=100)),
                ('start_date_ad', models.DateField(blank=True, null=True)),
                ('start_date_bs', models.CharField(blank=True, max_length=10)),
                ('end_date_ad', models.DateField(blank=True, null=True)),
                ('end_date_bs', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_history', to='students.student')),
            ],
            options={
                'ordering': ['student', '-start_date_ad'],
            },
        ),
        migrations.CreateModel(
            name='StudentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('inquiry', 'Inquiry'), ('pending', 'Pending'), ('active', 'Active'), ('on_break', 'On Break'), ('left', 'Left'), ('graduated', 'Graduated'), ('rejected', 'Rejected')], max_length=20)),
                ('to_status', models.CharField(choices=[('inquiry', 'Inquiry'), ('pending', 'Pending'), ('active', 'Active'), ('on_break', 'On Break'), ('left', 'Left'), ('graduated', 'Graduated'), ('rejected', 'Rejected')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_student_statuses', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.student')),
            ],
            options={
                'ordering': ['student', '-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'status'], name='students_st_organiz_d8da85_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch', 'status'], name='students_st_branch__4eab65_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_year', 'status'], name='students_st_academi_b0e76f_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['organization', 'admission_number'], name='students_st_organiz_c7f168_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='students_st_full_na_6ea9f7_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['phone'], name='students_st_phone_86fc06_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('organization', 'admission_number'), name='unique_admission_number_per_org'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['organization', 'document_type'], name='students_st_organiz_ca6d44_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['branch', 'document_type'], name='students_st_branch__8733cc_idx'),
        ),
        migrations.AddIndex(
            model_name='studentdocument',
            index=models.Index(fields=['academic_year', 'document_type'], name='students_st_academi_15ea36_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinquiry',
            index=models.Index(fields=['organization', 'status'], name='students_st_organiz_fe60f2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinquiry',
            index=models.Index(fields=['branch', 'status'], name='students_st_branch__af4300_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinquiry',
            index=models.Index(fields=['academic_year', 'status'], name='students_st_academi_6b23eb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinquiry',
            index=models.Index(fields=['student_full_name'], name='students_st_student_bdb356_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['category'], name='students_st_categor_04fafe_idx'),
        ),
        migrations.AddIndex(
            model_name='studentstatushistory',
            index=models.Index(fields=['to_status', 'changed_at'], name='students_st_to_stat_0ab89d_idx'),
        ),
    ]
