# Generated by Django 5.1.15 on 2026-05-15 05:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('bs_start_year', models.PositiveSmallIntegerField()),
                ('bs_end_year', models.PositiveSmallIntegerField()),
                ('bs_start_date', models.CharField(max_length=10)),
                ('bs_end_date', models.CharField(max_length=10)),
                ('ad_start_date', models.DateField(db_index=True)),
                ('ad_end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('soft_closed', 'Soft Closed'), ('hard_closed', 'Hard Closed'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__display_name', '-ad_start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('period_order', models.PositiveSmallIntegerField()),
                ('bs_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('bs_month_name', models.CharField(max_length=30)),
                ('bs_year', models.PositiveSmallIntegerField()),
                ('bs_start_date', models.CharField(max_length=10)),
                ('bs_end_date', models.CharField(max_length=10)),
                ('ad_start_date', models.DateField(db_index=True)),
                ('ad_end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('soft_closed', 'Soft Closed'), ('hard_closed', 'Hard Closed'), ('archived', 'Archived')], db_index=True, default='open', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_periods', to='organizations.organization')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academic.academicyear')),
            ],
            options={
                'ordering': ['academic_year', 'period_order'],
            },
        ),
        migrations.CreateModel(
            name='AcademicYearRollover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validating', 'Validating'), ('ready', 'Ready'), ('executed', 'Executed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('trial_balance_validated', models.BooleanField(default=False)),
                ('revenue_expense_closing_completed', models.BooleanField(default=False)),
                ('opening_balances_posted', models.BooleanField(default=False)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_academic_year_rollovers', to=settings.AUTH_USER_MODEL)),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rollovers_from', to='academic.academicyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_year_rollovers', to='organizations.organization')),
                ('to_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollovers_to', to='academic.academicyear')),
            ],
            options={
                'ordering': ['organization__display_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NepaliCalendarDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bs_date', models.CharField(db_index=True, max_length=10, unique=True)),
                ('bs_year', models.PositiveSmallIntegerField(db_index=True)),
                ('bs_month', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('bs_day', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('ad_date', models.DateField(db_index=True)),
                ('bs_month_name', models.CharField(max_length=30)),
                ('is_month_start', models.BooleanField(db_index=True, default=False)),
                ('is_month_end', models.BooleanField(db_index=True, default=False)),
                ('is_holiday', models.BooleanField(db_index=True, default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ad_date'],
                'indexes': [models.Index(fields=['bs_year', 'bs_month'], name='academic_ne_bs_year_a580f1_idx'), models.Index(fields=['ad_date'], name='academic_ne_ad_date_cbbdb7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['organization', 'status'], name='academic_ac_organiz_ae0bb1_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['organization', 'is_active'], name='academic_ac_organiz_cb1e42_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['bs_start_year', 'bs_end_year'], name='academic_ac_bs_star_0695c9_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['ad_start_date', 'ad_end_date'], name='academic_ac_ad_star_9e4b45_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_academic_year_name_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('organization',), name='unique_active_academic_year_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('ad_start_date__lte', models.F('ad_end_date'))), name='academic_year_ad_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['organization', 'status'], name='academic_ac_organiz_0ca080_idx'),
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['academic_year', 'status'], name='academic_ac_academi_44c41f_idx'),
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['academic_year', 'is_active'], name='academic_ac_academi_ee236e_idx'),
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['bs_year', 'bs_month'], name='academic_ac_bs_year_779f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='academicperiod',
            index=models.Index(fields=['ad_start_date', 'ad_end_date'], name='academic_ac_ad_star_380304_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.UniqueConstraint(fields=('academic_year', 'period_order'), name='unique_period_order_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.UniqueConstraint(fields=('academic_year', 'bs_year', 'bs_month'), name='unique_bs_month_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='academicperiod',
            constraint=models.CheckConstraint(condition=models.Q(('ad_start_date__lte', models.F('ad_end_date'))), name='academic_period_ad_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='academicyearrollover',
            index=models.Index(fields=['organization', 'status'], name='academic_ac_organiz_374054_idx'),
        ),
        migrations.AddIndex(
            model_name='academicyearrollover',
            index=models.Index(fields=['from_academic_year', 'status'], name='academic_ac_from_ac_f8352e_idx'),
        ),
    ]
