# Generated by Django 5.1.15 on 2026-05-15 05:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(max_length=50)),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20)),
                ('date_of_birth_ad', models.DateField(blank=True, null=True)),
                ('date_of_birth_bs', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('alternate_phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('experience_summary', models.TextField(blank=True)),
                ('joining_date_ad', models.DateField(blank=True, null=True)),
                ('joining_date_bs', models.CharField(blank=True, max_length=10)),
                ('photo_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('note', 'Note'), ('meeting', 'Meeting'), ('follow_up', 'Follow Up'), ('performance', 'Performance'), ('document', 'Document'), ('payment_related', 'Payment Related'), ('other', 'Other')], db_index=True, default='note', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('activity_date_ad', models.DateField(blank=True, null=True)),
                ('activity_date_bs', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_activities', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_activities', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_teacher_activities', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_activities', to='organizations.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='teachers.teacher')),
            ],
            options={
                'ordering': ['teacher', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_type', models.CharField(choices=[('monthly_cut_percentage', 'Monthly Cut Percentage'), ('package_course', 'Package Course'), ('fixed_monthly_salary', 'Fixed Monthly Salary')], max_length=40)),
                ('default_teacher_cut_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('package_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fixed_monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from_ad', models.DateField()),
                ('effective_from_bs', models.CharField(blank=True, max_length=10)),
                ('effective_to_ad', models.DateField(blank=True, null=True)),
                ('effective_to_bs', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_contracts', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_contracts', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_contracts', to='organizations.organization')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='teachers.teacher')),
            ],
            options={
                'ordering': ['teacher', '-effective_from_ad'],
            },
        ),
        migrations.CreateModel(
            name='TeacherStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], max_length=20)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_teacher_statuses', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='teachers.teacher')),
            ],
            options={
                'ordering': ['teacher', '-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['organization', 'status'], name='teachers_te_organiz_621100_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['branch', 'status'], name='teachers_te_branch__8eb104_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['organization', 'employee_number'], name='teachers_te_organiz_1964ff_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['phone'], name='teachers_te_phone_476fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['full_name'], name='teachers_te_full_na_e7daa7_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacher',
            constraint=models.UniqueConstraint(fields=('organization', 'employee_number'), name='unique_teacher_employee_number_per_org'),
        ),
        migrations.AddIndex(
            model_name='teacheractivity',
            index=models.Index(fields=['teacher', 'status'], name='teachers_te_teacher_f4138a_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheractivity',
            index=models.Index(fields=['academic_year', 'status'], name='teachers_te_academi_971947_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheractivity',
            index=models.Index(fields=['activity_type'], name='teachers_te_activit_9c4176_idx'),
        ),
        migrations.AddIndex(
            model_name='teacheractivity',
            index=models.Index(fields=['organization', 'branch'], name='teachers_te_organiz_15e769_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercontract',
            index=models.Index(fields=['teacher', 'is_active'], name='teachers_te_teacher_425ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercontract',
            index=models.Index(fields=['academic_year', 'is_active'], name='teachers_te_academi_bebb88_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercontract',
            index=models.Index(fields=['contract_type'], name='teachers_te_contrac_d21286_idx'),
        ),
        migrations.AddIndex(
            model_name='teachercontract',
            index=models.Index(fields=['organization', 'branch'], name='teachers_te_organiz_cf1fab_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachercontract',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('teacher', 'academic_year'), name='unique_active_teacher_contract_per_year'),
        ),
        migrations.AddConstraint(
            model_name='teachercontract',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to_ad__isnull', True), ('effective_from_ad__lte', models.F('effective_to_ad')), _connector='OR'), name='teacher_contract_effective_from_before_to'),
        ),
        migrations.AddIndex(
            model_name='teacherstatushistory',
            index=models.Index(fields=['to_status', 'changed_at'], name='teachers_te_to_stat_4906f1_idx'),
        ),
    ]
