# Generated by Django 5.1.15 on 2026-05-15 05:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('vat_pan_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('logo_path', models.CharField(blank=True, max_length=500)),
                ('default_currency', models.CharField(default='NPR', max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['display_name'],
                'indexes': [models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx'), models.Index(fields=['display_name'], name='organizatio_display_335b6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_main_branch', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__display_name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(max_length=100)),
                ('action_name', models.CharField(max_length=100)),
                ('minimum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('escalation_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalation_approval_rules', to='accounts.role')),
                ('required_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='required_approval_rules', to='accounts.role')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__display_name', 'module_name', 'action_name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=150)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('is_system_setting', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__display_name', 'key'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('rate_percentage', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tax_type', models.CharField(choices=[('vat', 'VAT'), ('pan', 'PAN'), ('service_tax', 'Service Tax'), ('other', 'Other')], default='vat', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__display_name', 'name', '-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_02ed07_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['organization', 'code'], name='organizatio_organiz_852766_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_main_branch'], name='organizatio_is_main_e3abc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_branch_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_branch', True)), fields=('organization',), name='unique_main_branch_per_organization'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_1837a6_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['branch', 'is_active'], name='organizatio_branch__2a632c_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrule',
            index=models.Index(fields=['module_name', 'action_name'], name='organizatio_module__06c57a_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsetting',
            index=models.Index(fields=['organization', 'key'], name='organizatio_organiz_c9ed68_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationsetting',
            index=models.Index(fields=['is_system_setting'], name='organizatio_is_syst_39d193_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationsetting',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='unique_setting_key_per_organization'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_b43f73_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['tax_type'], name='organizatio_tax_typ_5b727c_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['effective_from', 'effective_to'], name='organizatio_effecti_c5c192_idx'),
        ),
    ]
