# Generated by Django 5.1.15 on 2026-05-15 05:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_name', models.CharField(max_length=150)),
                ('batch_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(blank=True, default='', max_length=100)),
                ('start_date_ad', models.DateField(blank=True, null=True)),
                ('start_date_bs', models.CharField(blank=True, max_length=10)),
                ('expected_end_date_ad', models.DateField(blank=True, null=True)),
                ('expected_end_date_bs', models.CharField(blank=True, max_length=10)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('teacher_cut_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('teacher_payment_type', models.CharField(choices=[('monthly_cut_percentage', 'Monthly Cut Percentage'), ('package_course', 'Package Course'), ('fixed_monthly_salary', 'Fixed Monthly Salary')], default='monthly_cut_percentage', max_length=40)),
                ('payment_due_rule', models.CharField(choices=[('fixed_bs_day', 'Fixed BS Day'), ('end_of_bs_month', 'End Of BS Month'), ('manual', 'Manual')], default='fixed_bs_day', max_length=30)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_rooms', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_rooms', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_rooms', to='organizations.organization')),
                ('primary_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_class_rooms', to='teachers.teacher')),
            ],
            options={
                'ordering': ['academic_year', 'class_name', 'batch_name', 'section_name'],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('joined_date_ad', models.DateField()),
                ('joined_date_bs', models.CharField(blank=True, max_length=10)),
                ('end_date_ad', models.DateField(blank=True, null=True)),
                ('end_date_bs', models.CharField(blank=True, max_length=10)),
                ('left_date_ad', models.DateField(blank=True, null=True)),
                ('left_date_bs', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_break', 'On Break'), ('completed', 'Completed'), ('left', 'Left'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20)),
                ('enrollment_discount_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('enrollment_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('teacher_cut_percentage_override', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_enrollments', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_enrollments', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_enrollments', to='students.student')),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='classes.classroom')),
            ],
            options={
                'ordering': ['student', 'class_room', '-joined_date_ad'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='classes.classroom')),
            ],
            options={
                'ordering': ['class_room', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassTeacherTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_date_ad', models.DateField()),
                ('effective_date_bs', models.CharField(blank=True, max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_class_teacher_transfers', to=settings.AUTH_USER_MODEL)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_transfers', to='classes.classroom')),
                ('from_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='teachers.teacher')),
                ('to_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='teachers.teacher')),
            ],
            options={
                'ordering': ['class_room', '-effective_date_ad'],
            },
        ),
        migrations.CreateModel(
            name='StudentWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_attendance_date_ad', models.DateField()),
                ('last_attendance_date_bs', models.CharField(blank=True, max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_withdrawals', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_withdrawals', to='organizations.branch')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='classes.classenrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_withdrawals', to='organizations.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='students.student')),
            ],
            options={
                'ordering': ['student', '-last_attendance_date_ad'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='organizations.organization')),
            ],
            options={
                'ordering': ['subject_name'],
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='class_rooms', to='classes.subject'),
        ),
        migrations.CreateModel(
            name='ClassEnrollmentBreak',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('break_start_date_ad', models.DateField()),
                ('break_start_date_bs', models.CharField(blank=True, max_length=10)),
                ('expected_return_date_ad', models.DateField(blank=True, null=True)),
                ('expected_return_date_bs', models.CharField(blank=True, max_length=10)),
                ('actual_return_date_ad', models.DateField(blank=True, null=True)),
                ('actual_return_date_bs', models.CharField(blank=True, max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollment_breaks', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='classes.classenrollment')),
            ],
            options={
                'ordering': ['enrollment', '-break_start_date_ad'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='classes_cla_enrollm_1f40ce_idx'), models.Index(fields=['break_start_date_ad'], name='classes_cla_break_s_fb4712_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClassEnrollmentDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('sibling', 'Sibling'), ('merit', 'Merit'), ('hardship', 'Hardship'), ('other', 'Other')], max_length=30)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('effective_from_ad', models.DateField(blank=True, null=True)),
                ('effective_from_bs', models.CharField(blank=True, max_length=10)),
                ('effective_to_ad', models.DateField(blank=True, null=True)),
                ('effective_to_bs', models.CharField(blank=True, max_length=10)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_enrollment_discounts', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='classes.classenrollment')),
            ],
            options={
                'ordering': ['enrollment', '-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'status'], name='classes_cla_enrollm_37ee7a_idx'), models.Index(fields=['discount_type', 'status'], name='classes_cla_discoun_166101_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['organization', 'status'], name='classes_cla_organiz_1bdd56_idx'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['branch', 'status'], name='classes_cla_branch__27e5e6_idx'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['academic_year', 'status'], name='classes_cla_academi_209633_idx'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['student', 'status'], name='classes_cla_student_42fb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='classenrollment',
            index=models.Index(fields=['class_room', 'status'], name='classes_cla_class_r_3770a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'on_break'])), fields=('student', 'class_room'), name='unique_active_student_class_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('end_date_ad__isnull', True), ('joined_date_ad__lte', models.F('end_date_ad')), _connector='OR'), name='class_enrollment_joined_before_end'),
        ),
        migrations.AddConstraint(
            model_name='classenrollment',
            constraint=models.CheckConstraint(condition=models.Q(('left_date_ad__isnull', True), ('joined_date_ad__lte', models.F('left_date_ad')), _connector='OR'), name='class_enrollment_joined_before_left'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['class_room', 'is_active'], name='classes_cla_class_r_dbf7be_idx'),
        ),
        migrations.AddIndex(
            model_name='classschedule',
            index=models.Index(fields=['day_of_week', 'start_time'], name='classes_cla_day_of__0fa227_idx'),
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='class_schedule_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='classteachertransfer',
            index=models.Index(fields=['class_room', 'status'], name='classes_cla_class_r_c6213a_idx'),
        ),
        migrations.AddIndex(
            model_name='classteachertransfer',
            index=models.Index(fields=['from_teacher', 'status'], name='classes_cla_from_te_1efd7c_idx'),
        ),
        migrations.AddIndex(
            model_name='classteachertransfer',
            index=models.Index(fields=['to_teacher', 'status'], name='classes_cla_to_teac_4cba5c_idx'),
        ),
        migrations.AddIndex(
            model_name='classteachertransfer',
            index=models.Index(fields=['effective_date_ad'], name='classes_cla_effecti_2c66f6_idx'),
        ),
        migrations.AddIndex(
            model_name='studentwithdrawal',
            index=models.Index(fields=['organization', 'status'], name='classes_stu_organiz_3dcd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentwithdrawal',
            index=models.Index(fields=['branch', 'status'], name='classes_stu_branch__b11109_idx'),
        ),
        migrations.AddIndex(
            model_name='studentwithdrawal',
            index=models.Index(fields=['academic_year', 'status'], name='classes_stu_academi_d3260b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentwithdrawal',
            index=models.Index(fields=['student', 'status'], name='classes_stu_student_ad66e7_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['organization', 'is_active'], name='classes_sub_organiz_42770b_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['branch', 'is_active'], name='classes_sub_branch__a80cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['academic_year', 'is_active'], name='classes_sub_academi_917155_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_name'], name='classes_sub_subject_0370ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('organization', 'subject_code'), name='unique_subject_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['organization', 'status'], name='classes_cla_organiz_8e79eb_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['branch', 'status'], name='classes_cla_branch__df0ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['academic_year', 'status'], name='classes_cla_academi_3339d3_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['primary_teacher', 'status'], name='classes_cla_primary_fc1235_idx'),
        ),
        migrations.AddIndex(
            model_name='classroom',
            index=models.Index(fields=['class_name', 'batch_name', 'section_name'], name='classes_cla_class_n_edfac9_idx'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'academic_year', 'class_name', 'batch_name', 'section_name'), name='unique_class_batch_section_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.CheckConstraint(condition=models.Q(('expected_end_date_ad__isnull', True), ('start_date_ad__isnull', True), ('start_date_ad__lte', models.F('expected_end_date_ad')), _connector='OR'), name='class_room_start_before_expected_end'),
        ),
    ]
