# Generated by Django 5.1.15 on 2026-05-15 05:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('revenue', 'Revenue'), ('expense', 'Expense'), ('contra_asset', 'Contra Asset'), ('contra_revenue', 'Contra Revenue'), ('other_income', 'Other Income'), ('other_expense', 'Other Expense')], db_index=True, max_length=30)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('is_system_account', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'ordering': ['organization__display_name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(max_length=50)),
                ('entry_date_ad', models.DateField(db_index=True)),
                ('entry_date_bs', models.CharField(max_length=10)),
                ('posting_date_ad', models.DateField(blank=True, db_index=True, null=True)),
                ('posting_date_bs', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('narration', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('system', 'System'), ('opening', 'Opening'), ('closing', 'Closing'), ('reversal', 'Reversal')], db_index=True, default='manual', max_length=20)),
                ('source_app', models.CharField(blank=True, max_length=100)),
                ('source_model', models.CharField(blank=True, max_length=100)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
                ('source_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('reversed', 'Reversed'), ('void', 'Void')], db_index=True, default='draft', max_length=30)),
                ('is_system_generated', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='academic.academicperiod')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='organizations.organization')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_entries', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['organization__display_name', '-entry_date_ad', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountingDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('voucher', 'Voucher'), ('invoice', 'Invoice'), ('contract', 'Contract'), ('bank_statement', 'Bank Statement'), ('supporting_document', 'Supporting Document'), ('other', 'Other')], default='supporting_document', max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_documents', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_accounting_documents', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounting.journalentry')),
            ],
            options={
                'ordering': ['organization__display_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('debit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('student_id', models.UUIDField(blank=True, null=True)),
                ('teacher_id', models.UUIDField(blank=True, null=True)),
                ('class_id', models.UUIDField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='accounting.account')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entry_lines', to='organizations.branch')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entry_lines', to='organizations.organization')),
            ],
            options={
                'ordering': ['journal_entry', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('snapshot_at', models.DateTimeField()),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_snapshots', to='academic.academicperiod')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_snapshots', to='academic.academicyear')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_snapshots', to='accounting.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_snapshots', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__display_name', 'account__code', '-snapshot_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'is_active'], name='accounting__organiz_9451cf_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['organization', 'account_type'], name='accounting__organiz_da5c67_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='accounting__code_c93a8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_account_code_per_organization'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'status'], name='accounting__organiz_0fed0d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['organization', 'entry_date_ad'], name='accounting__organiz_b8f113_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['academic_year', 'status'], name='accounting__academi_71dc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['academic_period', 'status'], name='accounting__academi_a4c8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_app', 'source_model'], name='accounting__source__3b7319_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('organization', 'entry_number'), name='unique_journal_entry_number_per_org'),
        ),
        migrations.AddIndex(
            model_name='accountingdocument',
            index=models.Index(fields=['organization', 'document_type'], name='accounting__organiz_514ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingdocument',
            index=models.Index(fields=['journal_entry'], name='accounting__journal_53b4af_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingdocument',
            index=models.Index(fields=['reference_number'], name='accounting__referen_232cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['organization', 'account'], name='accounting__organiz_c8a7da_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry', 'account'], name='accounting__journal_fdc9d1_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['branch'], name='accounting__branch__7c27e3_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['student_id'], name='accounting__student_4f60e0_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['teacher_id'], name='accounting__teacher_691341_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['class_id'], name='accounting__class_i_65b983_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit_amount__gt', Decimal('0.00')), ('credit_amount', Decimal('0.00'))), models.Q(('credit_amount__gt', Decimal('0.00')), ('debit_amount', Decimal('0.00'))), _connector='OR'), name='journal_line_has_debit_or_credit_only'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gte', Decimal('0.00')), ('credit_amount__gte', Decimal('0.00'))), name='journal_line_amounts_non_negative'),
        ),
        migrations.AddIndex(
            model_name='ledgersnapshot',
            index=models.Index(fields=['organization', 'account'], name='accounting__organiz_8fc4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgersnapshot',
            index=models.Index(fields=['academic_year', 'academic_period'], name='accounting__academi_407075_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgersnapshot',
            index=models.Index(fields=['snapshot_at'], name='accounting__snapsho_6ab5ce_idx'),
        ),
    ]
