# Generated by Django 5.1.15 on 2026-05-15 06:10

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('classes', '0001_initial'),
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('fee_plan_type', models.CharField(choices=[('monthly', 'Monthly'), ('package', 'Package'), ('one_time', 'One Time'), ('custom', 'Custom')], default='monthly', max_length=20)),
                ('billing_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('one_time', 'One Time'), ('manual', 'Manual')], default='monthly', max_length=20)),
                ('payment_due_rule', models.CharField(choices=[('fixed_bs_day', 'Fixed BS Day'), ('end_of_bs_month', 'End Of BS Month'), ('manual', 'Manual')], default='fixed_bs_day', max_length=30)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_plans', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_plans', to='organizations.branch')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_plans', to='classes.classroom')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='organizations.organization')),
            ],
            options={
                'ordering': ['academic_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeePlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=255)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition'), ('admission', 'Admission'), ('exam', 'Exam'), ('material', 'Material'), ('fine', 'Fine'), ('other', 'Other')], default='tuition', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_recurring', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.feeplan')),
            ],
            options={
                'ordering': ['fee_plan', 'sort_order', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentAdvanceBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('applied_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('refunded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_advance_balances', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_advance_balances', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_advance_balances', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advance_balances', to='students.student')),
            ],
            options={
                'ordering': ['student', 'academic_year'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeeDue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_label', models.CharField(max_length=100)),
                ('due_date_ad', models.DateField(blank=True, db_index=True, null=True)),
                ('due_date_bs', models.CharField(blank=True, max_length=10)),
                ('original_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('written_off', 'Written Off')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_dues', to='academic.academicperiod')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_dues', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_fee_dues', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_dues', to='organizations.branch')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_student_fee_dues', to=settings.AUTH_USER_MODEL)),
                ('class_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_dues', to='classes.classenrollment')),
                ('class_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_dues', to='classes.classroom')),
                ('fee_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_dues', to='billing.feeplan')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_dues', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_dues', to='students.student')),
            ],
            options={
                'ordering': ['student', 'due_date_ad', 'period_label'],
            },
        ),
        migrations.CreateModel(
            name='StudentInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date_ad', models.DateField(db_index=True)),
                ('invoice_date_bs', models.CharField(blank=True, max_length=10)),
                ('due_date_ad', models.DateField(blank=True, db_index=True, null=True)),
                ('due_date_bs', models.CharField(blank=True, max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('written_off', 'Written Off')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_invoices', to='academic.academicperiod')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_invoices', to='academic.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_invoices', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_invoices', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='students.student')),
            ],
            options={
                'ordering': ['-invoice_date_ad', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='BillingWaiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waiver_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_waivers', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_billing_waivers', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_waivers', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_waivers', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_waivers', to='students.student')),
                ('fee_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_waivers', to='billing.studentfeedue')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_waivers', to='billing.studentinvoice')),
            ],
            options={
                'ordering': ['student', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingFine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fine_type', models.CharField(choices=[('late_fee', 'Late Fee'), ('penalty', 'Penalty'), ('other', 'Other')], default='late_fee', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('waived', 'Waived'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_fines', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_billing_fines', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_fines', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_fines', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_fines', to='students.student')),
                ('fee_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_fines', to='billing.studentfeedue')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_fines', to='billing.studentinvoice')),
            ],
            options={
                'ordering': ['student', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_type', models.CharField(choices=[('scholarship', 'Scholarship'), ('sibling', 'Sibling'), ('merit', 'Merit'), ('hardship', 'Hardship'), ('one_time', 'One Time'), ('bulk', 'Bulk'), ('other', 'Other')], max_length=30)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_discounts', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_billing_discounts', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_discounts', to='organizations.branch')),
                ('class_enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_discounts', to='classes.classenrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_discounts', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_discounts', to='students.student')),
                ('fee_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_discounts', to='billing.studentfeedue')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='billing_discounts', to='billing.studentinvoice')),
            ],
            options={
                'ordering': ['student', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentInvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition'), ('admission', 'Admission'), ('exam', 'Exam'), ('material', 'Material'), ('fine', 'Fine'), ('other', 'Other')], default='tuition', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('fee_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='billing.studentfeedue')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.studentinvoice')),
            ],
            options={
                'ordering': ['invoice', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('draft_receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date_ad', models.DateField(db_index=True)),
                ('payment_date_bs', models.CharField(blank=True, max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('online', 'Online'), ('cheque', 'Cheque'), ('wallet', 'Wallet'), ('other', 'Other')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('fine_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('net_received_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('is_advance_payment', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('voided', 'Voided'), ('refunded', 'Refunded')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_payments', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_payments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_payments', to='organizations.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_payments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='organizations.organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_student_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date_ad', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_allocated', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('fee_due', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.studentfeedue')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.studentinvoice')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='billing.studentinvoiceitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.studentpayment')),
            ],
            options={
                'ordering': ['payment', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_voucher_number', models.CharField(blank=True, max_length=100, null=True)),
                ('refund_date_ad', models.DateField(blank=True, db_index=True, null=True)),
                ('refund_date_bs', models.CharField(blank=True, max_length=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_refunds', to='academic.academicyear')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_student_refunds', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_refunds', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_refunds', to='organizations.organization')),
                ('original_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='billing.studentpayment')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_student_refunds', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_student_refunds', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='students.student')),
            ],
            options={
                'ordering': ['student', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='feeplan',
            index=models.Index(fields=['organization', 'is_active'], name='billing_fee_organiz_68c43a_idx'),
        ),
        migrations.AddIndex(
            model_name='feeplan',
            index=models.Index(fields=['branch', 'is_active'], name='billing_fee_branch__0ce01f_idx'),
        ),
        migrations.AddIndex(
            model_name='feeplan',
            index=models.Index(fields=['academic_year', 'is_active'], name='billing_fee_academi_8dc825_idx'),
        ),
        migrations.AddIndex(
            model_name='feeplan',
            index=models.Index(fields=['class_room', 'is_active'], name='billing_fee_class_r_3fd227_idx'),
        ),
        migrations.AddIndex(
            model_name='feeplan',
            index=models.Index(fields=['fee_plan_type', 'billing_frequency'], name='billing_fee_fee_pla_cd688a_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeplan',
            constraint=models.UniqueConstraint(fields=('organization', 'branch', 'academic_year', 'class_room', 'name'), name='unique_fee_plan_name_per_scope'),
        ),
        migrations.AddIndex(
            model_name='feeplanitem',
            index=models.Index(fields=['fee_plan', 'fee_type'], name='billing_fee_fee_pla_018e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='feeplanitem',
            index=models.Index(fields=['sort_order'], name='billing_fee_sort_or_2db5e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fee_plan_item_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='studentadvancebalance',
            index=models.Index(fields=['organization', 'academic_year'], name='billing_stu_organiz_0082f2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadvancebalance',
            index=models.Index(fields=['branch', 'academic_year'], name='billing_stu_branch__d66af3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadvancebalance',
            index=models.Index(fields=['student', 'academic_year'], name='billing_stu_student_ba90b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentadvancebalance',
            constraint=models.CheckConstraint(condition=models.Q(('opening_amount__gte', 0)), name='advance_opening_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentadvancebalance',
            constraint=models.CheckConstraint(condition=models.Q(('received_amount__gte', 0)), name='advance_received_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentadvancebalance',
            constraint=models.CheckConstraint(condition=models.Q(('applied_amount__gte', 0)), name='advance_applied_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentadvancebalance',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_amount__gte', 0)), name='advance_refunded_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentadvancebalance',
            constraint=models.CheckConstraint(condition=models.Q(('balance_amount__gte', 0)), name='advance_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='studentfeedue',
            index=models.Index(fields=['organization', 'status'], name='billing_stu_organiz_f369cb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeedue',
            index=models.Index(fields=['branch', 'status'], name='billing_stu_branch__b4800d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeedue',
            index=models.Index(fields=['academic_year', 'status'], name='billing_stu_academi_287d94_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeedue',
            index=models.Index(fields=['academic_period', 'status'], name='billing_stu_academi_c6b79c_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeedue',
            index=models.Index(fields=['student', 'status'], name='billing_stu_student_b3de14_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeedue',
            index=models.Index(fields=['class_enrollment', 'status'], name='billing_stu_class_e_52d8b4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeedue',
            index=models.Index(fields=['due_date_ad'], name='billing_stu_due_dat_f10f1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfeedue',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gte', 0)), name='fee_due_original_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentfeedue',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='fee_due_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentfeedue',
            constraint=models.CheckConstraint(condition=models.Q(('fine_amount__gte', 0)), name='fee_due_fine_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentfeedue',
            constraint=models.CheckConstraint(condition=models.Q(('net_amount__gte', 0)), name='fee_due_net_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentfeedue',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='fee_due_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentfeedue',
            constraint=models.CheckConstraint(condition=models.Q(('balance_amount__gte', 0)), name='fee_due_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['organization', 'status'], name='billing_stu_organiz_545046_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['branch', 'status'], name='billing_stu_branch__2229a4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['academic_year', 'status'], name='billing_stu_academi_1de893_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['academic_period', 'status'], name='billing_stu_academi_fd1772_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['student', 'status'], name='billing_stu_student_4e151f_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['invoice_number'], name='billing_stu_invoice_e740ab_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoice',
            index=models.Index(fields=['due_date_ad'], name='billing_stu_due_dat_049076_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='unique_invoice_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='invoice_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='invoice_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('fine_amount__gte', 0)), name='invoice_fine_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='invoice_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount__gte', 0)), name='invoice_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('balance_amount__gte', 0)), name='invoice_balance_non_negative'),
        ),
        migrations.AddIndex(
            model_name='billingwaiver',
            index=models.Index(fields=['organization', 'status'], name='billing_bil_organiz_944984_idx'),
        ),
        migrations.AddIndex(
            model_name='billingwaiver',
            index=models.Index(fields=['branch', 'status'], name='billing_bil_branch__0e222b_idx'),
        ),
        migrations.AddIndex(
            model_name='billingwaiver',
            index=models.Index(fields=['academic_year', 'status'], name='billing_bil_academi_ea2589_idx'),
        ),
        migrations.AddIndex(
            model_name='billingwaiver',
            index=models.Index(fields=['student', 'status'], name='billing_bil_student_a219c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingwaiver',
            constraint=models.CheckConstraint(condition=models.Q(('waiver_amount__gte', 0)), name='waiver_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='billingfine',
            index=models.Index(fields=['organization', 'status'], name='billing_bil_organiz_e6e3b7_idx'),
        ),
        migrations.AddIndex(
            model_name='billingfine',
            index=models.Index(fields=['branch', 'status'], name='billing_bil_branch__c5648e_idx'),
        ),
        migrations.AddIndex(
            model_name='billingfine',
            index=models.Index(fields=['academic_year', 'status'], name='billing_bil_academi_729ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='billingfine',
            index=models.Index(fields=['student', 'status'], name='billing_bil_student_d802e4_idx'),
        ),
        migrations.AddIndex(
            model_name='billingfine',
            index=models.Index(fields=['fine_type', 'status'], name='billing_bil_fine_ty_c1d8a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingfine',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='fine_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='billingdiscount',
            index=models.Index(fields=['organization', 'status'], name='billing_bil_organiz_4e0d99_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdiscount',
            index=models.Index(fields=['branch', 'status'], name='billing_bil_branch__5d980c_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdiscount',
            index=models.Index(fields=['academic_year', 'status'], name='billing_bil_academi_dced6e_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdiscount',
            index=models.Index(fields=['student', 'status'], name='billing_bil_student_605659_idx'),
        ),
        migrations.AddIndex(
            model_name='billingdiscount',
            index=models.Index(fields=['discount_type', 'status'], name='billing_bil_discoun_61f51f_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__isnull', True), ('discount_amount__gte', 0), _connector='OR'), name='billing_discount_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='studentinvoiceitem',
            index=models.Index(fields=['invoice', 'fee_type'], name='billing_stu_invoice_f147df_idx'),
        ),
        migrations.AddIndex(
            model_name='studentinvoiceitem',
            index=models.Index(fields=['fee_due'], name='billing_stu_fee_due_e42be3_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='invoice_item_quantity_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_amount__gte', 0)), name='invoice_item_unit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='invoice_item_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('fine_amount__gte', 0)), name='invoice_item_fine_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentinvoiceitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='invoice_item_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['organization', 'status'], name='billing_stu_organiz_8eec0a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['branch', 'status'], name='billing_stu_branch__05d2d1_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['academic_year', 'status'], name='billing_stu_academi_c654e5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['student', 'status'], name='billing_stu_student_aafc50_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['payment_method', 'status'], name='billing_stu_payment_df3041_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['receipt_number'], name='billing_stu_receipt_dc4771_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpayment',
            index=models.Index(fields=['draft_receipt_number'], name='billing_stu_draft_r_8c945e_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('receipt_number__isnull', False)), fields=('organization', 'receipt_number'), name='unique_receipt_number_per_org_when_set'),
        ),
        migrations.AddConstraint(
            model_name='studentpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('draft_receipt_number__isnull', False)), fields=('organization', 'draft_receipt_number'), name='unique_draft_receipt_number_per_org_when_set'),
        ),
        migrations.AddConstraint(
            model_name='studentpayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentpayment',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='payment_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentpayment',
            constraint=models.CheckConstraint(condition=models.Q(('fine_amount__gte', 0)), name='payment_fine_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='studentpayment',
            constraint=models.CheckConstraint(condition=models.Q(('net_received_amount__gte', 0)), name='payment_net_received_non_negative'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentallocation',
            index=models.Index(fields=['payment'], name='billing_stu_payment_aa08a4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentallocation',
            index=models.Index(fields=['fee_due'], name='billing_stu_fee_due_b12cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentallocation',
            index=models.Index(fields=['invoice'], name='billing_stu_invoice_6c1738_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpaymentallocation',
            index=models.Index(fields=['invoice_item'], name='billing_stu_invoice_701209_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_allocated__gte', 0)), name='payment_allocation_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='studentrefund',
            index=models.Index(fields=['organization', 'status'], name='billing_stu_organiz_e53439_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrefund',
            index=models.Index(fields=['branch', 'status'], name='billing_stu_branch__8d346a_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrefund',
            index=models.Index(fields=['academic_year', 'status'], name='billing_stu_academi_6f526e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrefund',
            index=models.Index(fields=['student', 'status'], name='billing_stu_student_7a56e3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrefund',
            index=models.Index(fields=['refund_voucher_number'], name='billing_stu_refund__1987f5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrefund',
            index=models.Index(fields=['refund_date_ad'], name='billing_stu_refund__965bde_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentrefund',
            constraint=models.UniqueConstraint(condition=models.Q(('refund_voucher_number__isnull', False)), fields=('organization', 'refund_voucher_number'), name='unique_refund_voucher_per_org_when_set'),
        ),
        migrations.AddConstraint(
            model_name='studentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='refund_amount_non_negative'),
        ),
    ]
